docs: まともにした
approvers/.github pull request #1
Opened 2022-05-10 12:36 UTC by mk-el

2022-05-10 13:00 UTC, MikuroXina requested changes

2022-05-10 13:00 UTC, MikuroXina commented on profile/README.md
> +[![logo](/profile/image/cover.png)](https://approvers.dev/)
ついでに alt テキストも読めるものに直してほしいです

2022-05-10 13:00 UTC, MikuroXina commented on profile/README.md
> +**高専生を中心に限界になった人々が限界状態で開発を行う Discord 鯖です。**
段落全体を Bold するくらいなら見出しにしておいてよいかと

2022-05-10 13:00 UTC, MikuroXina commented on profile/README.md
> +[Qiita](https://qiita.com/organizations/approvers)
単純に列挙するのであれば順序なしリストでよいかと. 原文もそうなっています.

もしくはリンクの見出しに変更して, それについて少し丁寧に説明を書いてもよいです.

2022-07-01 12:42 UTC, m2en commented on profile/README.md
> +**高専生を中心に限界になった人々が限界状態で開発を行う Discord 鯖です。**
見出しにするとGitHub上の仕様上、中央揃えにならないため、Boldにしています。

2022-07-01 12:47 UTC, MikuroXina commented on profile/README.md
> +**高専生を中心に限界になった人々が限界状態で開発を行う Discord 鯖です。**
そもそもこれ全体を囲っている `div` の `style="text-align: center;"` の中央揃えは機能していないので, そちらを消すことを考えても見出しでよいと思います

2022-07-10 14:27 UTC, m2en commented
https://github.com/approvers/.github/commit/921eea3c1d5a4e653f2a48054b5bdd3f5661b02f

何も考えずに `main` にやってしまい、意外といい感じになったので #1 は閉じます

(保護はONにします、、、すみません)

2022-07-10 14:27 UTC, closed without merging